<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error Handling</title>
</head>
<body>
    <script>
        class MathUtil{

            static sum(...numbers){

                if(numbers.length === 0){
                    throw new Error("Total parameter harus lebih dari 0");
                }
                let total = 0;
                for (const number of numbers) {
                    total += number;
                }
                return total;
            }
        }
        try{
            console.info(MathUtil.sum());
            console.info("Rizal");
            /*
            Jika terjadi error pada execute method MathUtil.sum(), maka kode program yg ada di bawahnya tidak akan dieksekusi
            melainkan akan diteruskan ke block catch, Block catch akan dijalankan apabila dalam execute kode di dlm block try terjadi suatu error.
            */
        } catch(error){
            console.info(`Terjadi error : ${error.message}`);
        } finally {
            /*
            Kode block finally ini akan selalu dieksekusi setelah eksekusi kode block try dan juga catch.
            Sukses ataupun error yang terjadi dalam execute kode program. Kode block finally ini akan tetap dieksekusi
            */
            console.info("Program Selesai!");
        }
        console.info("Pratama");

        class Counter{
            #counter = 1;

            next(){
                try{
                    return this.#counter;
                } finally {
                    this.#counter++;
                }
            }
        }
        const counter = new Counter();
        console.info(counter.next());
        console.info(counter.next());
        console.info(counter.next());
        console.info(counter.next());
        console.info(counter.next());
    </script>
</body>
</html>